// var message:string="Hello world";
// console.log(message);
// var greet='hi';
// console.log(greet);
var username:string='Kumaran';
var username:string;
var username='kumaran';
//let urname1: string | number;
urname1='Priya';
urname1=10;
console.log(urname1);